# Permalinks
permalink:           pretty

# Setup
title:               Stephan Bongers 
tagline:             'Stephan Bongers website' 
url:                 http://www.stephanbongers.com
shorturl:            stephanbongers.com
paginate:            1
baseurl:             ""

# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              'Stephan Bongers'
  url:               
  email:             srbongers@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/srbongers/srbongers.github.io
github_username: srbongers
google_scholar: https://scholar.google.nl/citations?user=UGhA4YgAAAAJ&hl=nl
linkedin: https://www.linkedin.com/in/stephan-r-bongers-968b8b39/


# This is the list of pages to include in the header of the website
pages_list:       
  Publications: '/publications'
  Talks: '/talks'
#  Archive: '/archive'
  Teaching: '/teaching'
  About: '/about'
  Contact: '/contact'
#  Feed: '/atom.xml'

# Jekyll-maps
#maps:
#  google:
#    api_key: AIzaSyBct2XbsTlBRdxDxxFubmyMIe2TPaSMUzE

# Google Analytics
google_analytics: UA-116419547-1

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-redirect-from
#  - jekyll-maps
